name: FIE463
channels:
  - defaults
dependencies:
  - python=3.13.11
  - numpy=2.3.5
  - scipy=1.16.3
  - matplotlib=3.10.7
  - pandas=2.3.3
  - openpyxl=3.1.5
  - notebook=7.5
  - ipykernel=6.31
  - ipython=9.7
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_server=2.17
  - scikit-learn=1.8
  - pip
  - pip:
    - yfinance>=1.0